### ISSUE TITLE
I wanna know the

### ISSUE THREAD

**Issue by PaulMou-aX** [dineshpinto/stm32f4#1]
Hi, could you tell me about what the specific model of the DDS module you used to implement AWG? I guess it's AD9833, isn't it?😊

**Comment by dineshpinto** [comment]
Hi, The AWG is from Keysight, the model is M8190A, [webpage here](https://www.keysight.com/us/en/product/M8190A/12-gsa-s-arbitrary-waveform-generator.html). This can generate arbitrary waveforms with very high fidelity over a large freq range :)

**Comment by PaulMou-aX** [comment]
Thanks very much!😊
